function capability = evaluate_powertrain_constraints( ...
        v_mps, tire, powertrain, Vbus_V)
%EVALUATE_POWERTRAIN_CONSTRAINTS Evaluate motor and TS drive capability.
%   gear_ratio is omega_motor/omega_wheel. Rolling radius is read only
%   from tire.rolling_radius_m. The returned force is powertrain capability
%   before tire traction limits.

arguments
    v_mps double {mustBeFinite, mustBeNonnegative}
    tire (1,1) struct
    powertrain (1,1) struct
    Vbus_V double {mustBeFinite, mustBeNonnegative} = []
end

powertrain = validate_powertrain_config(powertrain);
if ~isfield(tire, "rolling_radius_m") ...
        || ~isscalar(tire.rolling_radius_m) ...
        || ~isfinite(tire.rolling_radius_m) ...
        || tire.rolling_radius_m <= 0
    error("QSSLTS:PowertrainTire", ...
        "A positive finite tire.rolling_radius_m is required.");
end

v_mps = v_mps(:);
if isempty(Vbus_V)
    Vbus_V = powertrain.battery.V_bus_assumed_V;
end
Vbus_V = expandToSize(Vbus_V, numel(v_mps));
wheelSpeed_radps = v_mps / tire.rolling_radius_m;
motorSpeed_radps = wheelSpeed_radps * powertrain.gear_ratio;
motorSpeed_rpm = motorSpeed_radps * 60 / (2 * pi);

voltageEnvelope = calc_motor_voltage_envelope( ...
    motorSpeed_rpm, Vbus_V, powertrain);
tsCap = calc_ts_power_cap(Vbus_V, powertrain);
omegaRegularized_radps = max(motorSpeed_radps, ...
    voltageEnvelope.omega_regularization_radps);

rulePowerTorque_Nm = powerToTorque( ...
    tsCap.power_candidates_W.rule_power, powertrain, ...
    omegaRegularized_radps);
ruleCurrentTorque_Nm = powerToTorque( ...
    tsCap.power_candidates_W.rule_current, powertrain, ...
    omegaRegularized_radps);
batteryPowerTorque_Nm = powerToTorque( ...
    tsCap.power_candidates_W.battery_power, powertrain, ...
    omegaRegularized_radps);
batteryCurrentTorque_Nm = powerToTorque( ...
    tsCap.power_candidates_W.battery_current, powertrain, ...
    omegaRegularized_radps);
inverterPowerTorque_Nm = powerToTorque( ...
    tsCap.power_candidates_W.inverter_power, powertrain, ...
    omegaRegularized_radps);
inverterDcCurrentTorque_Nm = powerToTorque( ...
    tsCap.power_candidates_W.inverter_current, powertrain, ...
    omegaRegularized_radps);

motorPeakTorque_Nm = repmat(powertrain.motor.peak_torque_Nm, ...
    numel(v_mps), 1);
motorPhaseCurrentTorque_Nm = repmat( ...
    powertrain.motor.Kt_Nm_per_Arms ...
    * powertrain.motor.peak_phase_current_Arms, numel(v_mps), 1);
inverterPhaseCurrentTorque_Nm = repmat( ...
    powertrain.motor.Kt_Nm_per_Arms ...
    * powertrain.inverter.I_phase_peak_Arms, numel(v_mps), 1);
motorSpeedTorque_Nm = inf(numel(v_mps), 1);
cutoffRoundoff_rpm = 10 * eps(voltageEnvelope.stop_speed_rpm);
motorSpeedTorque_Nm(motorSpeed_rpm >= ...
    voltageEnvelope.stop_speed_rpm - cutoffRoundoff_rpm) = 0;
motorVoltageTorque_Nm = voltageEnvelope.linear_torque_limit_Nm;
motorVoltageTorque_Nm(motorSpeed_rpm ...
    <= voltageEnvelope.peak_load_speed_rpm) = inf;
motorPowerTorque_Nm = voltageEnvelope.power_torque_limit_Nm;

candidateNames = ["rule_power", "rule_current", "battery_power", ...
    "battery_current", "inverter_power", "inverter_dc_current", ...
    "inverter_phase_current", "motor_speed", "motor_voltage", ...
    "motor_power", "motor_peak_torque", "motor_phase_current"];
candidateLimiters = ["rule_power", "rule_current", "battery_power", ...
    "battery_current", "inverter_power", "inverter_current", ...
    "inverter_current", "motor_speed", "motor_voltage", ...
    "motor_power", "motor_torque", "motor_torque"];
candidateTorque_Nm = [rulePowerTorque_Nm, ruleCurrentTorque_Nm, ...
    batteryPowerTorque_Nm, batteryCurrentTorque_Nm, ...
    inverterPowerTorque_Nm, inverterDcCurrentTorque_Nm, ...
    inverterPhaseCurrentTorque_Nm, motorSpeedTorque_Nm, ...
    motorVoltageTorque_Nm, motorPowerTorque_Nm, ...
    motorPeakTorque_Nm, motorPhaseCurrentTorque_Nm];
[availableMotorTorque_Nm, index] = min(candidateTorque_Nm, [], 2);

capability.motor_speed_rpm = motorSpeed_rpm;
capability.wheel_speed_radps = wheelSpeed_radps;
capability.available_motor_torque_Nm = availableMotorTorque_Nm;
capability.available_motor_power_W = availableMotorTorque_Nm ...
    .* motorSpeed_radps;
capability.available_wheel_force_N = availableMotorTorque_Nm ...
    * powertrain.gear_ratio * powertrain.drivetrain_efficiency ...
    / tire.rolling_radius_m;
capability.limiter = candidateLimiters(index).';
capability.candidate_names = candidateNames;
capability.candidate_limiters = candidateLimiters;
capability.candidate_torque_Nm = candidateTorque_Nm;
capability.candidates.rule_power_torque_Nm = rulePowerTorque_Nm;
capability.candidates.rule_current_torque_Nm = ruleCurrentTorque_Nm;
capability.candidates.battery_power_torque_Nm = batteryPowerTorque_Nm;
capability.candidates.battery_current_torque_Nm = batteryCurrentTorque_Nm;
capability.candidates.inverter_power_torque_Nm = inverterPowerTorque_Nm;
capability.candidates.inverter_dc_current_torque_Nm = ...
    inverterDcCurrentTorque_Nm;
capability.candidates.inverter_phase_current_torque_Nm = ...
    inverterPhaseCurrentTorque_Nm;
capability.candidates.motor_speed_torque_Nm = motorSpeedTorque_Nm;
capability.candidates.motor_voltage_torque_Nm = motorVoltageTorque_Nm;
capability.candidates.motor_power_torque_Nm = motorPowerTorque_Nm;
capability.candidates.motor_peak_torque_Nm = motorPeakTorque_Nm;
capability.candidates.motor_phase_current_torque_Nm = ...
    motorPhaseCurrentTorque_Nm;
capability.tsac_power_cap_W = tsCap.tsac_power_cap_W;
capability.tsac_limiter = tsCap.limiter;
capability.dc_current_limits_A = tsCap.dc_current_limits_A;
capability.phase_current_limits_Arms.motor = ...
    powertrain.motor.peak_phase_current_Arms;
capability.phase_current_limits_Arms.inverter = ...
    powertrain.inverter.I_phase_peak_Arms;
capability.effective_voltage_V = voltageEnvelope.effective_voltage_V;
capability.voltage_scenario = voltageEnvelope.voltage_scenario;
capability.thermal_feasibility_evaluated = false;
capability.regen_enabled = false;
end

function torque_Nm = powerToTorque(tsacPower_W, powertrain, omega_radps)
mechanicalPower_W = max(tsacPower_W ...
    - powertrain.battery.P_ts_aux_W, 0) ...
    * powertrain.inverter.eta_const * powertrain.motor.eta_const;
torque_Nm = mechanicalPower_W ./ omega_radps;
end

function value = expandToSize(value, count)
value = value(:);
if isscalar(value)
    value = repmat(value, count, 1);
elseif numel(value) ~= count
    error("QSSLTS:PowertrainQuerySize", ...
        "Vbus_V must be scalar or match v_mps.");
end
end
