function powertrain = validate_powertrain_config(powertrain)
%VALIDATE_POWERTRAIN_CONFIG Validate the frozen composite EV configuration.

arguments
    powertrain (1,1) struct
end

requiredTop = ["enabled", "motor_count", "layout", "gear_ratio", ...
    "drivetrain_efficiency", "motor", "battery", "inverter", "rules"];
requireFields(powertrain, requiredTop, "powertrain");
actualTop = string(fieldnames(powertrain));
if ~isequal(sort(actualTop), sort(requiredTop(:)))
    error("QSSLTS:PowertrainConfig", ...
        "powertrain must contain exactly the frozen top-level fields.");
end

if ~(islogical(powertrain.enabled) || isnumeric(powertrain.enabled)) ...
        || ~isscalar(powertrain.enabled) ...
        || ~ismember(double(powertrain.enabled), [0, 1])
    error("QSSLTS:PowertrainConfig", ...
        "powertrain.enabled must be a scalar logical value.");
end
if ~isscalar(powertrain.motor_count) || powertrain.motor_count ~= 1
    error("QSSLTS:PowertrainMotorCount", ...
        "V1 supports exactly one motor.");
end
layout = upper(string(powertrain.layout));
if ~isscalar(layout) || ~ismember(layout, ["FWD", "RWD", "AWD"])
    error("QSSLTS:PowertrainConfig", ...
        "powertrain.layout must be FWD, RWD, or AWD.");
end
requirePositiveFinite(powertrain.gear_ratio, "powertrain.gear_ratio");
requireEfficiency(powertrain.drivetrain_efficiency, ...
    "powertrain.drivetrain_efficiency");

motorFields = ["max_mechanical_speed_rpm", "physical_peak_power_W", ...
    "physical_peak_power_rpm", "physical_cont_power_W", ...
    "peak_torque_Nm", "cont_torque_Nm", ...
    "required_voltage_peak_power_V", "peak_phase_current_Arms", ...
    "cont_phase_current_Arms", "Kv_no_load_rpm_per_V", ...
    "Kv_nominal_load_rpm_per_V", "Kv_peak_load_rpm_per_V", ...
    "Kt_Nm_per_Arms", "eta_const", "thermal_model_enabled"];
requireFields(powertrain.motor, motorFields, "powertrain.motor");
motorValues = [powertrain.motor.max_mechanical_speed_rpm, ...
    powertrain.motor.physical_peak_power_W, ...
    powertrain.motor.physical_peak_power_rpm, ...
    powertrain.motor.physical_cont_power_W, ...
    powertrain.motor.peak_torque_Nm, powertrain.motor.cont_torque_Nm, ...
    powertrain.motor.required_voltage_peak_power_V, ...
    powertrain.motor.peak_phase_current_Arms, ...
    powertrain.motor.cont_phase_current_Arms, ...
    powertrain.motor.Kv_no_load_rpm_per_V, ...
    powertrain.motor.Kv_nominal_load_rpm_per_V, ...
    powertrain.motor.Kv_peak_load_rpm_per_V, ...
    powertrain.motor.Kt_Nm_per_Arms];
requirePositiveFinite(motorValues, "powertrain.motor ratings");
requireEfficiency(powertrain.motor.eta_const, ...
    "powertrain.motor.eta_const");
if ~isscalar(powertrain.motor.thermal_model_enabled) ...
        || logical(powertrain.motor.thermal_model_enabled)
    error("QSSLTS:PowertrainThermalUnsupported", ...
        "V1 requires motor.thermal_model_enabled=false.");
end

batteryFields = ["V_max_V", "V_nominal_V", "V_min_V", ...
    "V_bus_assumed_V", "E_nominal_kWh", "SOC_init", "SOC_min", ...
    "P_discharge_peak_W", "I_discharge_peak_A", ...
    "eta_discharge", "P_ts_aux_W"];
requireFields(powertrain.battery, batteryFields, "powertrain.battery");
requirePositiveFinite([powertrain.battery.V_max_V, ...
    powertrain.battery.V_nominal_V, ...
    powertrain.battery.V_min_V, powertrain.battery.V_bus_assumed_V, ...
    powertrain.battery.E_nominal_kWh, ...
    powertrain.battery.P_discharge_peak_W, ...
    powertrain.battery.I_discharge_peak_A], "powertrain.battery ratings");
if powertrain.battery.V_min_V > powertrain.battery.V_nominal_V ...
        || powertrain.battery.V_nominal_V > powertrain.battery.V_max_V ...
        || powertrain.battery.V_bus_assumed_V > powertrain.battery.V_max_V
    error("QSSLTS:PowertrainConfig", ...
        "Battery voltage values are inconsistent.");
end
if ~isRealFiniteNumericScalar(powertrain.battery.SOC_init) ...
        || ~isRealFiniteNumericScalar(powertrain.battery.SOC_min) ...
        || powertrain.battery.SOC_min < 0 ...
        || powertrain.battery.SOC_init > 1 ...
        || powertrain.battery.SOC_min >= powertrain.battery.SOC_init
    error("QSSLTS:PowertrainConfig", ...
        "Battery SOC limits are inconsistent.");
end
requireEfficiency(powertrain.battery.eta_discharge, ...
    "powertrain.battery.eta_discharge");
if ~isscalar(powertrain.battery.P_ts_aux_W) ...
        || ~isfinite(powertrain.battery.P_ts_aux_W) ...
        || powertrain.battery.P_ts_aux_W < 0
    error("QSSLTS:PowertrainConfig", ...
        "battery.P_ts_aux_W must be finite and nonnegative.");
end

inverterFields = ["V_dc_max_V", "P_dc_peak_W", ...
    "I_dc_peak_A", "I_phase_peak_Arms", "eta_const"];
requireFields(powertrain.inverter, inverterFields, "powertrain.inverter");
requirePositiveFinite([powertrain.inverter.V_dc_max_V, ...
    powertrain.inverter.P_dc_peak_W, ...
    powertrain.inverter.I_dc_peak_A, ...
    powertrain.inverter.I_phase_peak_Arms], ...
    "powertrain.inverter ratings");
requireEfficiency(powertrain.inverter.eta_const, ...
    "powertrain.inverter.eta_const");

ruleFields = ["max_ts_voltage_V", "max_ts_power_W", ...
    "max_ts_current_A", "regen_enabled_in_model"];
requireFields(powertrain.rules, ruleFields, "powertrain.rules");
requirePositiveFinite([powertrain.rules.max_ts_voltage_V, ...
    powertrain.rules.max_ts_power_W, ...
    powertrain.rules.max_ts_current_A], "powertrain.rules limits");
if ~isscalar(powertrain.rules.regen_enabled_in_model) ...
        || logical(powertrain.rules.regen_enabled_in_model)
    error("QSSLTS:PowertrainRegenUnsupported", ...
        "V1 requires rules.regen_enabled_in_model=false.");
end
end

function valid = isRealFiniteNumericScalar(value)
valid = isnumeric(value) && isreal(value) ...
    && isscalar(value) && isfinite(value);
end

function requireFields(value, required, name)
if ~isstruct(value) || ~isscalar(value) ...
        || ~all(isfield(value, cellstr(required)))
    error("QSSLTS:PowertrainConfig", ...
        "%s is missing required fields.", name);
end
end

function requirePositiveFinite(value, name)
if isempty(value) || any(~isfinite(value), "all") ...
        || any(value <= 0, "all")
    error("QSSLTS:PowertrainConfig", ...
        "%s must contain positive finite values.", name);
end
end

function requireEfficiency(value, name)
if ~isscalar(value) || ~isfinite(value) || value <= 0 || value > 1
    error("QSSLTS:PowertrainConfig", ...
        "%s must be in (0, 1].", name);
end
end
