function state = qsslts_gui_default_state(projectRoot)
%QSSLTS_GUI_DEFAULT_STATE Return the complete GUI baseline in SI units.

arguments
    projectRoot (1, 1) string = ""
end

state = struct( ...
    track_preset="tianji_kart_QSS_track_closed", ...
    track_source_file= ...
        "data/track/tianji_kart_QSS_track_closed.csv", ...
    endurance_num_laps=26, ...
    endurance_safety_factor=1.10, ...
    vehicle_preset="vehicle_baseline", ...
    vehicle_mass_total_kg=300, ...
    vehicle_wheelbase_m=1.668, ...
    vehicle_track_front_m=1.200, ...
    vehicle_track_rear_m=1.200, ...
    vehicle_cg_height_m=0.250, ...
    vehicle_front_static_frac=0.40, ...
    vehicle_inertia_Iz_kgm2=120, ...
    vehicle_front_lateral_load_transfer_frac=0.50, ...
    vehicle_drivetrain_layout="RWD", ...
    tire_preset="tire_load_sensitive_baseline", ...
    tire_Fz_ref_N=750, ...
    tire_mu_x_ref=1.60, ...
    tire_mu_y_ref=1.60, ...
    tire_load_sensitivity_x=-0.08, ...
    tire_load_sensitivity_y=-0.08, ...
    tire_combined_n=2, ...
    tire_rolling_radius_m=0.2286, ...
    aero_preset="aero_baseline", ...
    aero_CLA_m2=3.0, ...
    aero_CDA_m2=1.2, ...
    aero_front_downforce_frac=0.50, ...
    brake_preset="brake_baseline", ...
    brake_enabled=true, ...
    brake_force_limit_enabled=false, ...
    brake_max_total_brake_force_N=10000, ...
    brake_max_decel_g_mechanical=2.0, ...
    brake_max_total_brake_torque_Nm=1400, ...
    brake_front_bias=0.60, ...
    powertrain_preset="powertrain_emrax228_hvcc_demo", ...
    powertrain_gear_ratio=4.369334602435052, ...
    powertrain_drivetrain_efficiency=0.90, ...
    motor_max_mechanical_speed_rpm=6500, ...
    motor_physical_peak_power_W=104e3, ...
    motor_physical_peak_power_rpm=4500, ...
    motor_physical_cont_power_W=75e3, ...
    motor_peak_torque_Nm=220, ...
    motor_cont_torque_Nm=130, ...
    motor_required_voltage_peak_power_V=830, ...
    motor_peak_phase_current_Arms=235, ...
    motor_cont_phase_current_Arms=120, ...
    motor_Kv_no_load_rpm_per_V=10.14, ...
    motor_Kv_nominal_load_rpm_per_V=7.85, ...
    motor_Kv_peak_load_rpm_per_V=5.65, ...
    motor_Kt_Nm_per_Arms=0.94, ...
    motor_eta_const=0.94, ...
    battery_V_max_V=600, ...
    battery_V_nominal_V=540, ...
    battery_V_min_V=450, ...
    battery_V_bus_assumed_V=600, ...
    battery_E_nominal_kWh=8, ...
    battery_SOC_init=0.95, ...
    battery_SOC_min=0.10, ...
    battery_P_discharge_peak_W=100e3, ...
    battery_I_discharge_peak_A=300, ...
    battery_eta_discharge=0.98, ...
    battery_P_ts_aux_W=500, ...
    inverter_V_dc_max_V=600, ...
    inverter_P_dc_peak_W=100e3, ...
    inverter_I_dc_peak_A=300, ...
    inverter_I_phase_peak_Arms=250, ...
    inverter_eta_const=0.97, ...
    options_v_max_mps=45, ...
    options_v_grid_step_mps=0.5, ...
    options_solver_tolerance_mps=1e-8);

if strlength(projectRoot) > 0
    envelopeFile = fullfile(projectRoot, "data", "tire", ...
        "Hoosier_16x75_10_R20.qss-envelope.mat");
    tire = load_qss_tire_envelope(envelopeFile);
    state.tire_preset = "tire_mfeval_qss_local";
    state.tire_Fz_ref_N = tire.Fz_ref_N;
    state.tire_mu_x_ref = tire.mu_x_ref;
    state.tire_mu_y_ref = tire.mu_y_ref;
    state.tire_load_sensitivity_x = tire.load_sensitivity_x;
    state.tire_load_sensitivity_y = tire.load_sensitivity_y;
    state.tire_combined_n = tire.combined_n;
end
end
