function write_qsslts_gui_config(filePath, state)
%WRITE_QSSLTS_GUI_CONFIG Write GUI parameters as versioned JSON.

arguments
    filePath {mustBeTextScalar}
    state (1,1) struct
end

filePath = string(filePath);
if ismissing(filePath) || strlength(strtrim(filePath)) == 0
    error("QSSLTS:GuiConfig", "Configuration path must not be empty.");
end
state = validate_qsslts_gui_state(state);

document = struct();
document.schema = "qsslts-gui-parameters";
document.schema_version = 2;
document.units = "SI";
document.track = struct( ...
    preset=state.track_preset, ...
    source_file=state.track_source_file);
document.endurance = struct( ...
    num_laps=state.endurance_num_laps, ...
    safety_factor=state.endurance_safety_factor);
document.vehicle = struct( ...
    preset=state.vehicle_preset, ...
    mass_total_kg=state.vehicle_mass_total_kg, ...
    wheelbase_m=state.vehicle_wheelbase_m, ...
    track_front_m=state.vehicle_track_front_m, ...
    track_rear_m=state.vehicle_track_rear_m, ...
    cg_height_m=state.vehicle_cg_height_m, ...
    front_static_frac=state.vehicle_front_static_frac, ...
    inertia_Iz_kgm2=state.vehicle_inertia_Iz_kgm2, ...
    front_lateral_load_transfer_frac= ...
        state.vehicle_front_lateral_load_transfer_frac, ...
    drivetrain_layout=state.vehicle_drivetrain_layout);
document.tire = struct( ...
    preset=state.tire_preset, ...
    Fz_ref_N=state.tire_Fz_ref_N, ...
    mu_x_ref=state.tire_mu_x_ref, ...
    mu_y_ref=state.tire_mu_y_ref, ...
    load_sensitivity_x=state.tire_load_sensitivity_x, ...
    load_sensitivity_y=state.tire_load_sensitivity_y, ...
    combined_n=state.tire_combined_n, ...
    rolling_radius_m=state.tire_rolling_radius_m);
document.aero = struct( ...
    preset=state.aero_preset, ...
    CLA_m2=state.aero_CLA_m2, ...
    CDA_m2=state.aero_CDA_m2, ...
    front_downforce_frac=state.aero_front_downforce_frac);
document.brake = struct( ...
    preset=state.brake_preset, ...
    enabled=state.brake_enabled, ...
    force_limit_enabled=state.brake_force_limit_enabled, ...
    max_total_brake_force_N=state.brake_max_total_brake_force_N, ...
    max_decel_g_mechanical=state.brake_max_decel_g_mechanical, ...
    max_total_brake_torque_Nm= ...
        state.brake_max_total_brake_torque_Nm, ...
    front_bias=state.brake_front_bias);

motor = struct( ...
    max_mechanical_speed_rpm=state.motor_max_mechanical_speed_rpm, ...
    physical_peak_power_W=state.motor_physical_peak_power_W, ...
    physical_peak_power_rpm=state.motor_physical_peak_power_rpm, ...
    physical_cont_power_W=state.motor_physical_cont_power_W, ...
    peak_torque_Nm=state.motor_peak_torque_Nm, ...
    cont_torque_Nm=state.motor_cont_torque_Nm, ...
    required_voltage_peak_power_V= ...
        state.motor_required_voltage_peak_power_V, ...
    peak_phase_current_Arms=state.motor_peak_phase_current_Arms, ...
    cont_phase_current_Arms=state.motor_cont_phase_current_Arms, ...
    Kv_no_load_rpm_per_V=state.motor_Kv_no_load_rpm_per_V, ...
    Kv_nominal_load_rpm_per_V= ...
        state.motor_Kv_nominal_load_rpm_per_V, ...
    Kv_peak_load_rpm_per_V=state.motor_Kv_peak_load_rpm_per_V, ...
    Kt_Nm_per_Arms=state.motor_Kt_Nm_per_Arms, ...
    eta_const=state.motor_eta_const);
battery = struct( ...
    V_max_V=state.battery_V_max_V, ...
    V_nominal_V=state.battery_V_nominal_V, ...
    V_min_V=state.battery_V_min_V, ...
    V_bus_assumed_V=state.battery_V_bus_assumed_V, ...
    E_nominal_kWh=state.battery_E_nominal_kWh, ...
    SOC_init=state.battery_SOC_init, ...
    SOC_min=state.battery_SOC_min, ...
    P_discharge_peak_W=state.battery_P_discharge_peak_W, ...
    I_discharge_peak_A=state.battery_I_discharge_peak_A, ...
    eta_discharge=state.battery_eta_discharge, ...
    P_ts_aux_W=state.battery_P_ts_aux_W);
inverter = struct( ...
    V_dc_max_V=state.inverter_V_dc_max_V, ...
    P_dc_peak_W=state.inverter_P_dc_peak_W, ...
    I_dc_peak_A=state.inverter_I_dc_peak_A, ...
    I_phase_peak_Arms=state.inverter_I_phase_peak_Arms, ...
    eta_const=state.inverter_eta_const);
document.powertrain = struct( ...
    preset=state.powertrain_preset, ...
    gear_ratio=state.powertrain_gear_ratio, ...
    drivetrain_efficiency=state.powertrain_drivetrain_efficiency, ...
    motor=motor, battery=battery, inverter=inverter);
document.options = struct( ...
    v_max_mps=state.options_v_max_mps, ...
    v_grid_step_mps=state.options_v_grid_step_mps, ...
    solver_tolerance_mps=state.options_solver_tolerance_mps);

jsonText = jsonencode(document, PrettyPrint=true);
[fileId, message] = fopen(filePath, "w", "n", "UTF-8");
if fileId < 0
    error("QSSLTS:GuiConfig", ...
        "Unable to open configuration file: %s", message);
end
cleanup = onCleanup(@() fclose(fileId));
count = fprintf(fileId, "%s\n", jsonText);
if count < strlength(jsonText)
    error("QSSLTS:GuiConfig", ...
        "Failed to write the complete configuration file.");
end
clear cleanup
end
