function [active, limiter] = classify_active_constraints( ...
        v_mps, ax_mps2, ay_mps2, vLat_mps, lateralLimiter, ggv, ...
        powertrainResult, options)
%CLASSIFY_ACTIVE_CONSTRAINTS Return pointwise multi-active and primary labels.

arguments
    v_mps double {mustBeFinite, mustBeNonnegative}
    ax_mps2 double {mustBeFinite}
    ay_mps2 double {mustBeFinite}
    vLat_mps double {mustBeNonnegative}
    lateralLimiter
    ggv (1,1) struct
    powertrainResult (1,1) struct
    options (1,1) struct = struct()
end

options = default_qss_options(options);
v_mps = v_mps(:);
ax_mps2 = ax_mps2(:);
ay_mps2 = ay_mps2(:);
vLat_mps = vLat_mps(:);
lateralLimiter = string(lateralLimiter(:));
nPoint = numel(v_mps);
validateInputs(nPoint, ax_mps2, ay_mps2, vLat_mps, ...
    lateralLimiter, powertrainResult);

utilizationTolerance = 1e-3;
active.lateral = lateralLimiter == "lateral" ...
    & isNear(v_mps, vLat_mps);
active.brake = false(nPoint, 1);
active.traction = isUtilized( ...
    powertrainResult.wheel_force_used_N, ...
    powertrainResult.traction_force_available_N, ...
    utilizationTolerance);

candidateLimiters = string(powertrainResult.candidate_limiters);
candidateAvailable_Nm = ...
    powertrainResult.candidate_torque_available_Nm;
candidateUsed_Nm = powertrainResult.motor_torque_used_Nm;
candidateActive = isfinite(candidateAvailable_Nm) ...
    & candidateAvailable_Nm > 0 ...
    & candidateUsed_Nm >= (1 - utilizationTolerance) ...
    .* candidateAvailable_Nm;
active.motor_torque = any(candidateActive(:, ...
    candidateLimiters == "motor_torque"), 2);
active.motor_power = any(candidateActive(:, ...
    candidateLimiters == "motor_power"), 2);
active.motor_speed = powertrainResult.motor_speed_rpm ...
    >= powertrainResult.motor_stop_speed_rpm ...
    - speedTolerance(powertrainResult.motor_speed_rpm, ...
    powertrainResult.motor_stop_speed_rpm);
active.motor_voltage = any(candidateActive(:, ...
    candidateLimiters == "motor_voltage"), 2);
active.rule_power = any(candidateActive(:, ...
    candidateLimiters == "rule_power"), 2);
active.rule_current = any(candidateActive(:, ...
    candidateLimiters == "rule_current"), 2);
active.battery_power = any(candidateActive(:, ...
    candidateLimiters == "battery_power"), 2);
active.battery_current = any(candidateActive(:, ...
    candidateLimiters == "battery_current"), 2);
active.inverter_power = any(candidateActive(:, ...
    candidateLimiters == "inverter_power"), 2);
active.inverter_current = any(candidateActive(:, ...
    candidateLimiters == "inverter_current"), 2);
speedCap_mps = min(options.v_max_mps, ggv.v_mps(end));
active.top_speed = v_mps >= speedCap_mps ...
    - speedTolerance(v_mps, speedCap_mps);

for iPoint = 1:nPoint
    cap = interp_ggv(ggv, v_mps(iPoint), ...
        ay_mps2(iPoint) / options.gravity_mps2, options);
    active.brake(iPoint) = cap.is_feasible ...
        && isNear(ax_mps2(iPoint), cap.ax_min_mps2);
end

priority = ["lateral", "brake", "top_speed", "rule_power", ...
    "rule_current", "battery_power", "battery_current", ...
    "inverter_power", "inverter_current", "motor_speed", ...
    "motor_voltage", "motor_power", "motor_torque", "traction"];
limiter = strings(nPoint, 1);
for iPriority = 1:numel(priority)
    name = priority(iPriority);
    select = strlength(limiter) == 0 & active.(name);
    limiter(select) = name;
end

forceTolerance_N = 0.01 + 1e-3 * max( ...
    abs(powertrainResult.wheel_force_used_N), ...
    abs(powertrainResult.wheel_force_available_N));
coasting = strlength(limiter) == 0 ...
    & powertrainResult.wheel_force_used_N <= forceTolerance_N;
limiter(coasting) = "coasting";
limiter(strlength(limiter) == 0) = "unconstrained";
end

function result = isNear(value, reference)
result = abs(value - reference) <= 0.01 ...
    + 1e-3 * max(abs(value), abs(reference));
end

function tolerance = speedTolerance(value, reference)
tolerance = 0.01 + 1e-3 * max(abs(value), abs(reference));
end

function result = isUtilized(used, available, tolerance)
result = isfinite(available) & available > 0 ...
    & used >= (1 - tolerance) .* available;
end

function validateInputs(nPoint, ax_mps2, ay_mps2, vLat_mps, ...
        lateralLimiter, powertrainResult)
if numel(ax_mps2) ~= nPoint || numel(ay_mps2) ~= nPoint ...
        || numel(vLat_mps) ~= nPoint || numel(lateralLimiter) ~= nPoint
    error("QSSLTS:ActiveConstraintShape", ...
        "All pointwise lap arrays must have equal length.");
end
required = ["motor_speed_rpm", "motor_stop_speed_rpm", ...
    "motor_torque_used_Nm", "wheel_force_available_N", ...
    "wheel_force_used_N", "traction_force_available_N", ...
    "candidate_limiters", "candidate_torque_available_Nm"];
if ~all(isfield(powertrainResult, cellstr(required))) ...
        || size(powertrainResult.candidate_torque_available_Nm, 1) ...
        ~= nPoint ...
        || size(powertrainResult.candidate_torque_available_Nm, 2) ...
        ~= numel(powertrainResult.candidate_limiters)
    error("QSSLTS:ActiveConstraintPowertrain", ...
        "Powertrain point results are incomplete or inconsistent.");
end
end
