function fig = plot_ggv_surface(result, speedSlices_mps)
%PLOT_GGV_SURFACE Plot GGV surfaces, slices, and actual lap points.

arguments
    result (1,1) struct
    speedSlices_mps = []
end

validateResult(result);
ggv = result.ggv_used;
vGrid_mps = ggv.v_mps(:);
ayGrid_g = ggv.ay_g(:).';
if isempty(speedSlices_mps)
    defaultIndex = unique(round(linspace(1, numel(vGrid_mps), 3)), ...
        "stable");
    speedSlices_mps = vGrid_mps(defaultIndex);
end
validateSpeedSlices(speedSlices_mps, vGrid_mps);
speedSlices_mps = speedSlices_mps(:);

axMax_g = ggv.ax_max_g;
axMin_g = ggv.ax_min_g;
axMax_g(~ggv.feasible) = NaN;
axMin_g(~ggv.feasible) = NaN;
sliceAxMax_g = interp1(vGrid_mps, axMax_g, speedSlices_mps, "linear");
sliceAxMin_g = interp1(vGrid_mps, axMin_g, speedSlices_mps, "linear");
actualAy_g = result.ay_mps2(:) / ggv.gravity_mps2;
actualAx_g = result.ax_mps2(:) / ggv.gravity_mps2;
[axBoundary_g, ayBoundary_g, speedBoundary_mps] = ...
    prepare_ggv_boundary_surface(ggv);

fig = figure(Name="GGV Capability");
layout = tiledlayout(fig, 1, 2, Padding="compact", ...
    TileSpacing="compact");

axSurface = nexttile(layout);
surf(axSurface, axBoundary_g, ayBoundary_g, speedBoundary_mps, ...
    speedBoundary_mps, FaceAlpha=0.82, ...
    EdgeColor=[0.15 0.25 0.28], EdgeAlpha=0.24, ...
    Tag="ggv-envelope-surface", DisplayName="GGV capability boundary");
hold(axSurface, "on");
scatter3(axSurface, actualAx_g, actualAy_g, result.v_mps(:), ...
    18, result.v_mps(:), "filled", Tag="actual-ggv-points-3d", ...
    DisplayName="Actual lap points");
grid(axSurface, "on");
xlabel(axSurface, "Ax (g)");
ylabel(axSurface, "Ay (g)");
zlabel(axSurface, "Speed (m/s)");
title(axSurface, "GGV Capability Surface");
view(axSurface, [-38 26]);
legend(axSurface, Location="best");
colorbar(axSurface);

axSlices = nexttile(layout);
hold(axSlices, "on");
for index = 1:numel(speedSlices_mps)
    speed_mps = speedSlices_mps(index);
    plot(axSlices, ayGrid_g, sliceAxMax_g(index, :), ...
        LineWidth=1.2, DisplayName=sprintf( ...
        "Ax max @ %.1f m/s", speed_mps));
    plot(axSlices, ayGrid_g, sliceAxMin_g(index, :), "--", ...
        LineWidth=1.2, DisplayName=sprintf( ...
        "Ax min @ %.1f m/s", speed_mps));
end
scatter(axSlices, actualAy_g, actualAx_g, 18, result.v_mps(:), ...
    "filled", Tag="actual-ggv-points", ...
    DisplayName="Actual lap points");
grid(axSlices, "on");
xlabel(axSlices, "Ay (g)");
ylabel(axSlices, "Ax (g)");
title(axSlices, "GGV Speed Slices");
legend(axSlices, Location="best");
end

function validateResult(result)
requiredResult = ["ggv_used", "v_mps", "ax_mps2", "ay_mps2"];
requiredGgv = ["v_mps", "ay_g", "ax_max_g", "ax_min_g", ...
    "feasible", "gravity_mps2"];
if ~all(isfield(result, cellstr(requiredResult))) ...
        || ~isstruct(result.ggv_used) || ~isscalar(result.ggv_used) ...
        || ~all(isfield(result.ggv_used, cellstr(requiredGgv)))
    error("QSSLTS:PlotGGVShape", ...
        "result.ggv_used and actual lap state fields are required.");
end
ggv = result.ggv_used;
vGrid_mps = ggv.v_mps;
ayGrid_g = ggv.ay_g;
nSpeed = numel(vGrid_mps);
nLateral = numel(ayGrid_g);
expectedSize = [nSpeed nLateral];
if ~isnumeric(vGrid_mps) || ~isreal(vGrid_mps) ...
        || ~isvector(vGrid_mps) || nSpeed < 2 ...
        || any(~isfinite(vGrid_mps(:))) ...
        || any(diff(vGrid_mps(:)) <= 0) ...
        || ~isnumeric(ayGrid_g) || ~isreal(ayGrid_g) ...
        || ~isvector(ayGrid_g) || nLateral < 2 ...
        || any(~isfinite(ayGrid_g(:))) ...
        || any(diff(ayGrid_g(:)) <= 0) ...
        || ~isnumeric(ggv.ax_max_g) || ~isreal(ggv.ax_max_g) ...
        || ~isequal(size(ggv.ax_max_g), expectedSize) ...
        || any(~isfinite(ggv.ax_max_g(:))) ...
        || ~isnumeric(ggv.ax_min_g) || ~isreal(ggv.ax_min_g) ...
        || ~isequal(size(ggv.ax_min_g), expectedSize) ...
        || any(~isfinite(ggv.ax_min_g(:))) ...
        || ~islogical(ggv.feasible) ...
        || ~isequal(size(ggv.feasible), expectedSize) ...
        || ~isnumeric(ggv.gravity_mps2) ...
        || ~isscalar(ggv.gravity_mps2) ...
        || ~isfinite(ggv.gravity_mps2) || ggv.gravity_mps2 <= 0
    error("QSSLTS:PlotGGVShape", ...
        "GGV grids and Nv-by-Nay capability arrays are inconsistent.");
end
nPoint = numel(result.v_mps);
actualValues = {result.v_mps, result.ax_mps2, result.ay_mps2};
for index = 1:numel(actualValues)
    value = actualValues{index};
    if ~isnumeric(value) || ~isreal(value) || ~isvector(value) ...
            || numel(value) ~= nPoint || nPoint < 1 ...
            || any(~isfinite(value(:)))
        error("QSSLTS:PlotGGVShape", ...
            "Actual v, Ax, and Ay must be equal-length finite vectors.");
    end
end
end

function validateSpeedSlices(speedSlices_mps, vGrid_mps)
if ~isnumeric(speedSlices_mps) || ~isreal(speedSlices_mps) ...
        || ~isvector(speedSlices_mps) || isempty(speedSlices_mps) ...
        || any(~isfinite(speedSlices_mps(:))) ...
        || any(speedSlices_mps(:) < vGrid_mps(1)) ...
        || any(speedSlices_mps(:) > vGrid_mps(end))
    error("QSSLTS:PlotGGVSpeedSlices", ...
        "Speed slices must be finite and inside the GGV speed grid.");
end
end
