classdef evaluateLapPowertrainTest < matlab.unittest.TestCase
    properties
        Vehicle
        Tire
        Aero
        Powertrain
        Options
    end

    methods (TestClassSetup)
        function buildFixture(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "src"), IncludingSubfolders=true));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "data"), IncludingSubfolders=true));
            testCase.Vehicle = vehicle_baseline();
            testCase.Tire = tire_simple_baseline();
            testCase.Aero = struct("enabled", false);
            testCase.Powertrain = powertrain_emrax228_hvcc_demo();
            testCase.Options = default_qss_options();
        end
    end

    methods (Test)
        function testNodeCapabilityUsageAndCandidateShapes(testCase)
            track = evaluateLapPowertrainTest.makeClosedTrack([8; 9; 10]);
            speed_mps = [5; 8; 10];
            ax_mps2 = [1; 0; -1];
            ay_mps2 = zeros(3, 1);

            result = evaluate_lap_powertrain(track, speed_mps, ...
                ax_mps2, ay_mps2, testCase.Vehicle, testCase.Tire, ...
                testCase.Aero, testCase.Powertrain, testCase.Options);

            pointFields = ["motor_speed_rpm", ...
                "motor_torque_available_Nm", "motor_torque_used_Nm", ...
                "wheel_force_available_N", "wheel_force_used_N", ...
                "tsac_power_cap_W", "tsac_power_used_W", ...
                "tsac_dc_current_used_A", ...
                "battery_dc_current_used_A", ...
                "inverter_dc_current_used_A", ...
                "motor_phase_current_used_Arms", ...
                "inverter_phase_current_used_Arms", ...
                "V_bus_V", ...
                "effective_voltage_V", ...
                "traction_force_available_N", ...
                "powertrain_force_available_N", ...
                "motor_stop_speed_rpm"];
            pointValues = arrayfun(@(name) result.(name), ...
                pointFields, UniformOutput=false);
            testCase.verifyTrue(all(cellfun( ...
                @(value) isequal(size(value), [3 1]), pointValues)));
            testCase.verifySize(result.candidate_names, [1 12]);
            testCase.verifySize(result.candidate_limiters, [1 12]);
            testCase.verifySize(result.candidate_torque_available_Nm, [3 12]);
            testCase.verifyEqual(result.effective_voltage_V, ...
                testCase.Powertrain.battery.V_bus_assumed_V ...
                * ones(3, 1), AbsTol=0);
            testCase.verifyEqual(result.V_bus_V, ...
                testCase.Powertrain.battery.V_bus_assumed_V ...
                * ones(3, 1), AbsTol=0);
            testCase.verifyFalse(result.thermal_feasibility_evaluated);
            testCase.verifyFalse(result.regen_enabled);
        end

        function testDriveUsageUsesNodeAccelerationAndEfficiencyChain(testCase)
            track = evaluateLapPowertrainTest.makeClosedTrack([8; 9; 10]);
            speed_mps = [5; 8; 10];
            ax_mps2 = [1; 0; -1];
            ay_mps2 = zeros(3, 1);
            expectedWheelForce_N = testCase.Vehicle.mass.total_kg;
            expectedMotorTorque_Nm = expectedWheelForce_N ...
                * testCase.Tire.rolling_radius_m ...
                / (testCase.Powertrain.gear_ratio ...
                * testCase.Powertrain.drivetrain_efficiency);
            expectedTsPower_W = expectedWheelForce_N * speed_mps(1) ...
                / (testCase.Powertrain.drivetrain_efficiency ...
                * testCase.Powertrain.inverter.eta_const ...
                * testCase.Powertrain.motor.eta_const) ...
                + testCase.Powertrain.battery.P_ts_aux_W;

            result = evaluate_lap_powertrain(track, speed_mps, ...
                ax_mps2, ay_mps2, testCase.Vehicle, testCase.Tire, ...
                testCase.Aero, testCase.Powertrain, testCase.Options);

            testCase.verifyEqual(result.wheel_force_used_N(1), ...
                expectedWheelForce_N, AbsTol=1e-10);
            testCase.verifyEqual(result.motor_torque_used_Nm(1), ...
                expectedMotorTorque_Nm, AbsTol=1e-10);
            testCase.verifyEqual(result.tsac_power_used_W(1), ...
                expectedTsPower_W, AbsTol=1e-10);
            testCase.verifyEqual(result.tsac_dc_current_used_A(1), ...
                expectedTsPower_W ...
                / testCase.Powertrain.battery.V_bus_assumed_V, ...
                AbsTol=1e-12);
            testCase.verifyEqual(result.battery_dc_current_used_A(1), ...
                expectedTsPower_W ...
                / testCase.Powertrain.battery.V_bus_assumed_V, ...
                AbsTol=1e-12);
            testCase.verifyEqual(result.inverter_dc_current_used_A(1), ...
                (expectedTsPower_W ...
                - testCase.Powertrain.battery.P_ts_aux_W) ...
                / testCase.Powertrain.battery.V_bus_assumed_V, ...
                AbsTol=1e-12);
            testCase.verifyEqual(result.motor_phase_current_used_Arms(1), ...
                expectedMotorTorque_Nm ...
                / testCase.Powertrain.motor.Kt_Nm_per_Arms, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.inverter_phase_current_used_Arms(1), ...
                expectedMotorTorque_Nm ...
                / testCase.Powertrain.motor.Kt_Nm_per_Arms, ...
                AbsTol=1e-12);
        end

        function testOpenTrackLastNodeUsageIsZero(testCase)
            track = evaluateLapPowertrainTest.makeOpenTrack([8; 9]);
            speed_mps = [5; 8; 10];
            ax_mps2 = [1; 1; 1];
            ay_mps2 = zeros(3, 1);

            result = evaluate_lap_powertrain(track, speed_mps, ...
                ax_mps2, ay_mps2, testCase.Vehicle, testCase.Tire, ...
                testCase.Aero, testCase.Powertrain, testCase.Options);

            lastUsage = [result.motor_torque_used_Nm(end), ...
                result.wheel_force_used_N(end), ...
                result.tsac_power_used_W(end), ...
                result.tsac_dc_current_used_A(end), ...
                result.battery_dc_current_used_A(end), ...
                result.inverter_dc_current_used_A(end), ...
                result.motor_phase_current_used_Arms(end), ...
                result.inverter_phase_current_used_Arms(end)];
            testCase.verifyEqual(lastUsage, zeros(1, 8), AbsTol=0);
            testCase.verifyGreaterThan( ...
                result.powertrain_force_available_N(end), 0);
            testCase.verifyGreaterThan( ...
                result.traction_force_available_N(end), 0);
        end

        function testActualLateralAccelerationReducesTractionCapability(testCase)
            track = evaluateLapPowertrainTest.makeClosedTrack([10; 10]);
            speed_mps = 10 * ones(2, 1);
            ax_mps2 = zeros(2, 1);
            zeroAy_mps2 = zeros(2, 1);
            lateralAy_mps2 = 0.8 * testCase.Options.gravity_mps2 ...
                * ones(2, 1);

            zeroAy = evaluate_lap_powertrain(track, speed_mps, ...
                ax_mps2, zeroAy_mps2, testCase.Vehicle, testCase.Tire, ...
                testCase.Aero, testCase.Powertrain, testCase.Options);
            lateralAy = evaluate_lap_powertrain(track, speed_mps, ...
                ax_mps2, lateralAy_mps2, testCase.Vehicle, ...
                testCase.Tire, testCase.Aero, testCase.Powertrain, ...
                testCase.Options);

            testCase.verifyLessThan(lateralAy.traction_force_available_N, ...
                zeroAy.traction_force_available_N);
            testCase.verifyEqual(lateralAy.powertrain_force_available_N, ...
                zeroAy.powertrain_force_available_N, AbsTol=1e-10);
        end
    end

    methods (Static, Access=private)
        function track = makeOpenTrack(ds_m)
            track.ds_m = ds_m(:);
            track.s_m = [0; cumsum(track.ds_m)];
            track.kappa_1pm = zeros(numel(track.s_m), 1);
            track.is_closed = false;
        end

        function track = makeClosedTrack(ds_m)
            track.ds_m = ds_m(:);
            track.s_m = [0; cumsum(track.ds_m(1:end-1))];
            track.kappa_1pm = zeros(numel(track.s_m), 1);
            track.is_closed = true;
        end
    end
end
