classdef formalExampleDocumentationContractTest < matlab.unittest.TestCase
    properties
        ProjectRoot
        ExampleFile
    end

    methods (TestClassSetup)
        function locateProject(testCase)
            testCase.ProjectRoot = fileparts(fileparts(fileparts( ...
                mfilename("fullpath"))));
            testCase.ExampleFile = fullfile(testCase.ProjectRoot, ...
                "examples", "run_qss_emrax228_hvcc_energy_demo.m");
        end
    end

    methods (Test)
        function testFormalExampleFileExists(testCase)
            testCase.verifyTrue(isfile(testCase.ExampleFile));
        end

        function testFormalExampleConfigurationContract(testCase)
            testCase.assumeTrue(isfile(testCase.ExampleFile));
            content = string(fileread(testCase.ExampleFile));
            required = [ ...
                "data", "track", "tianji_kart_QSS_track_closed.csv", ...
                "read_track_csv", "vehicle_baseline", ...
                "tire_load_sensitive_baseline", "aero_baseline", ...
                "powertrain_emrax228_hvcc_demo", "brake_baseline", ...
                '"num_laps", 26', '"safety_factor", 1.10', ...
                "run_qss_lap"];

            testCase.verifyContainsAll(content, required);
            testCase.verifyFalse(contains(content, "models.ggv"));
            testCase.verifyFalse(contains(content, "isfile(trackFile)"));
        end

        function testFormalExampleOutputContract(testCase)
            testCase.assumeTrue(isfile(testCase.ExampleFile));
            content = string(fileread(testCase.ExampleFile));
            required = ["result.lap_time_s", "max(result.v_mps)", ...
                "max(result.powertrain.motor_speed_rpm)", ...
                "max(result.powertrain.tsac_power_used_W)", ...
                "max(result.powertrain.tsac_dc_current_used_A)", ...
                "summarize_limiter_usage(result)", ...
                "result.energy.E_lap_ts_kWh", ...
                "result.energy.E_lap_stored_kWh", ...
                "result.energy.E_nominal_required_kWh"];

            testCase.verifyContainsAll(content, required);
        end

        function testFormalExamplePlotsAndCaveats(testCase)
            testCase.assumeTrue(isfile(testCase.ExampleFile));
            content = string(fileread(testCase.ExampleFile));
            required = ["plot_track_speed_map(result)", ...
                "plot_powertrain_energy_result(result)", ...
                "plot_ggv_surface(result)", ...
                "Thermal feasibility not evaluated", ...
                "Regenerative braking disabled", ...
                "First-order endurance estimate"];

            testCase.verifyContainsAll(content, required);
        end

        function testReadmeReleaseAndEntryPoint(testCase)
            content = testCase.readProjectFile("README.md");
            required = ["MATLAB R2026a", ...
                "run_qss_emrax228_hvcc_energy_demo.m", ...
                "data/track/tianji_kart_QSS_track_closed.csv", ...
                "本地未跟踪", "reference/", "固定赛线", ...
                "单圈能量", "耐久容量", ...
                "plot_track_speed_map", ...
                "plot_powertrain_energy_result", "plot_ggv_surface"];

            testCase.verifyContainsAll(content, required);
            testCase.verifyFalse(contains(content, "独立 7DOF"));
            testCase.verifyFalse(contains(content, "能耗模型、"));
        end

        function testProjectScopeContract(testCase)
            content = testCase.readProjectFile("docs/project-scope.md");
            required = ["固定赛线 QSS", "单圈能量", "耐久容量估算", ...
                "7DOF、14DOF 或全赛道瞬态整车模型", ...
                "自由赛线和驾驶员模型", "固定 DC 电压", ...
                "无再生", "无热状态", "F_rolling=0", ...
                "相对筛选", "实车绝对精度"];

            testCase.verifyContainsAll(content, required);
            testCase.verifyFalse(contains(content, ...
                "7DOF 的直线加速、直线制动"));
        end

        function testArchitectureContract(testCase)
            content = testCase.readProjectFile("docs/architecture.md");
            required = ["actual Ay", "calc_drive_limit", ...
                "generate_model_ggv", "run_qss_lap", ...
                "result.powertrain", "result.energy", ...
                "N → 1", "速度剖面收敛后", "Sensitivity/DOE"];

            testCase.verifyContainsAll(content, required);
            testCase.verifyFalse(contains(content, "src/dof7"));
        end

        function testTrackAndPowertrainInterfaceContract(testCase)
            content = testCase.readProjectFile("docs/model_interface.md");
            required = ["s_m,kappa_1pm", ...
                "s_m,x_m,y_m,curvature_1_m,track_width_m", ...
                "curvature_1_m → kappa_1pm", "N 个唯一节点", ...
                "重复闭合端点", "closure_is_estimated", ...
                "857.461445744691", "1.461445744691", ...
                "enabled, motor_count, layout, gear_ratio", ...
                "drivetrain_efficiency, motor, battery, inverter, rules", ...
                "gear_ratio = omega_motor / omega_wheel", ...
                "tire.rolling_radius_m", "enabled=false", ...
                "QSSLTS:PowertrainConfig"];

            testCase.verifyContainsAll(content, required);
            testCase.verifyFalse(contains(content, ...
                "powertrain.max_total_wheel_torque_Nm`："));
        end

        function testResultAndAnalysisInterfaceContract(testCase)
            content = testCase.readProjectFile("docs/model_interface.md");
            required = ["result.limiter", "result.active_constraints", ...
                "lateral, brake, traction", "motor_torque", ...
                "motor_power", "motor_speed", "motor_voltage", ...
                "rule_power", "rule_current", "battery_power", ...
                "battery_current", "inverter_power", ...
                "inverter_current", "top_speed", ...
                "lateral > brake > top_speed", ...
                "0.01 m/s", "0.01 m/s²", "0.01 rpm", ...
                "相对 `1e-3`", ...
                "result.powertrain", "result.energy", ...
                "E_lap_ts_kWh", "E_lap_stored_kWh", ...
                "E_nominal_required_kWh", "26", "1.10", ...
                "inverter_power_W", "gear_ratio", ...
                "AnalysisRulesImmutable"];

            testCase.verifyContainsAll(content, required);
        end

        function testPowertrainEnergyDocumentationContract(testCase)
            content = testCase.readProjectFile( ...
                "docs/powertrain_energy_model.md");
            required = ["Formula Student Rules 2026 v1.1", ...
                "600 VDC", "80 kW", "500 A", ...
                "104 kW@4500 rpm", "830 V", ...
                "P_voltage = motor.physical_peak_power_W", ...
                "T_linear = motor.peak_torque_Nm", ...
                "保守工程推断", "DC A", "phase Arms", ...
                "actual", "14 个字段", "N→1", ...
                "26", "1.10", "固定 DC 母线电压", ...
                "常数效率", "无回生", "无热状态", ...
                "F_rolling=0", "重复同一个已求得的最小圈速剖面", ...
                "plot_track_speed_map(result)", ...
                "plot_powertrain_energy_result(result)", ...
                "plot_ggv_surface(result", ...
                "FSG rule reference", "inverter_power_W", ...
                "AnalysisRulesImmutable"];

            testCase.verifyContainsAll(content, required);
            testCase.verifyFalse(contains(content, ...
                "旧的扁平动力接口暂时保留"));
        end
    end

    methods (Access=private)
        function content = readProjectFile(testCase, relativePath)
            content = string(fileread(fullfile( ...
                testCase.ProjectRoot, relativePath)));
        end

        function verifyContainsAll(testCase, content, required)
            for token = required
                testCase.verifyTrue(contains(content, token), ...
                    "Missing required token: " + token);
            end
        end
    end
end
