classdef sensitivityDoeTest < matlab.unittest.TestCase
    properties
        BaseConfig
    end

    properties (TestParameter)
        requestedParameter = struct( ...
            'cgHeight', struct( ...
                'name', "cg_height_m", ...
                'path', "vehicle.mass.cg_height_m", ...
                'value', 0.31), ...
            'yawInertia', struct( ...
                'name', "inertia_Iz_kgm2", ...
                'path', "vehicle.inertia.Iz_kgm2", ...
                'value', 135), ...
            'frontAxleLoad', struct( ...
                'name', "front_static_frac", ...
                'path', "vehicle.mass.front_static_frac", ...
                'value', 0.43), ...
            'wheelbase', struct( ...
                'name', "wheelbase_m", ...
                'path', "vehicle.geometry.wheelbase_m", ...
                'value', 1.60), ...
            'frontTrack', struct( ...
                'name', "track_front_m", ...
                'path', "vehicle.geometry.track_front_m", ...
                'value', 1.21), ...
            'rearTrack', struct( ...
                'name', "track_rear_m", ...
                'path', "vehicle.geometry.track_rear_m", ...
                'value', 1.19), ...
            'cla', struct( ...
                'name', "cla_m2", ...
                'path', "models.aero.CLA_m2", ...
                'value', 3.30), ...
            'cda', struct( ...
                'name', "cda_m2", ...
                'path', "models.aero.CDA_m2", ...
                'value', 1.25), ...
            'aeroBalance', struct( ...
                'name', "front_downforce_frac", ...
                'path', "models.aero.front_downforce_frac", ...
                'value', 0.46), ...
            'gearRatio', struct( ...
                'name', "gear_ratio", ...
                'path', "models.powertrain.gear_ratio", ...
                'value', 4.60))
        invalidRequestedParameter = struct( ...
            'zeroYawInertia', struct( ...
                'name', "inertia_Iz_kgm2", 'value', 0), ...
            'invalidFrontAxleLoad', struct( ...
                'name', "front_static_frac", 'value', 1.1), ...
            'nonfiniteWheelbase', struct( ...
                'name', "wheelbase_m", 'value', NaN))
    end

    methods (TestClassSetup)
        function buildFixture(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "src"), IncludingSubfolders=true));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "data"), IncludingSubfolders=true));
            track.s_m = [0; 20; 40; 60; 80; 100];
            track.ds_m = 20 * ones(6, 1);
            track.kappa_1pm = [0; 0.08; 0.08; 0; -0.10; -0.04];
            track.is_closed = true;
            testCase.BaseConfig.track = track;
            testCase.BaseConfig.vehicle = vehicle_baseline();
            testCase.BaseConfig.models.tire = tire_load_sensitive_baseline();
            testCase.BaseConfig.models.aero = struct("enabled", false);
            testCase.BaseConfig.models.powertrain = ...
                powertrain_emrax228_hvcc_demo();
            testCase.BaseConfig.models.brake = brake_baseline();
            testCase.BaseConfig.models.endurance = struct( ...
                "num_laps", 1, "safety_factor", 1.0);
            options = default_qss_options();
            options.v_grid_mps = [0; 10; 20; 30; 40; 45];
            options.ay_grid_g = -2:0.2:2;
            options.calibration_smoothing_window = 1;
            testCase.BaseConfig.options = options;
        end
    end

    methods (Test)
        function testRequestedParameterMapsToRuntimeField( ...
                testCase, requestedParameter)
            config = apply_analysis_parameter(testCase.BaseConfig, ...
                requestedParameter.name, requestedParameter.value);

            actual = get_nested_field(config, requestedParameter.path);

            testCase.verifyEqual(actual, requestedParameter.value, ...
                AbsTol=1e-12);
        end

        function testInvalidRequestedParameterIsRejected( ...
                testCase, invalidRequestedParameter)
            action = @() apply_analysis_parameter(testCase.BaseConfig, ...
                invalidRequestedParameter.name, ...
                invalidRequestedParameter.value);

            testCase.verifyError(action, "QSSLTS:AnalysisParameter");
        end

        function testMassSweepReturnsPhysicalOrdering(testCase)
            sweep.parameter = "vehicle.mass.total_kg";
            sweep.values = [280; 300; 320];

            result = run_sensitivity_sweep(testCase.BaseConfig, sweep);

            testCase.verifyEqual(height(result.table), 3);
            testCase.verifyEqual(result.calibration_mode, "theory_only");
            testCase.verifyGreaterThan(result.table.lap_time_s(3), ...
                result.table.lap_time_s(1));
        end

        function testDoeRunsTwentyCasesAndSorts(testCase)
            mass_kg = repelem([280; 300; 320; 340], 5);
            inverter_power_W = repmat((60000:10000:100000).', 4, 1);
            cases = table(mass_kg, inverter_power_W);

            result = run_doe(testCase.BaseConfig, cases);

            testCase.verifyEqual(height(result.ranking), 20);
            testCase.verifyTrue(all(isfinite(result.ranking.lap_time_s)));
            testCase.verifyGreaterThanOrEqual(diff(result.ranking.lap_time_s), ...
                -1e-12 * ones(19, 1));
            testCase.verifyGreaterThanOrEqual(result.fastest_case_id, 1);
            testCase.verifyLessThanOrEqual(result.slowest_case_id, 20);
        end

        function testDoeAcceptsRequestedVehicleAeroAndGearingColumns( ...
                testCase)
            cg_height_m = 0.26;
            inertia_Iz_kgm2 = 126;
            front_static_frac = 0.41;
            wheelbase_m = 1.65;
            track_front_m = 1.19;
            track_rear_m = 1.18;
            cla_m2 = 3.1;
            cda_m2 = 1.15;
            front_downforce_frac = 0.48;
            gear_ratio = 4.45;
            cases = table(cg_height_m, inertia_Iz_kgm2, ...
                front_static_frac, wheelbase_m, track_front_m, ...
                track_rear_m, cla_m2, cda_m2, ...
                front_downforce_frac, gear_ratio);

            result = run_doe(testCase.BaseConfig, cases);

            testCase.verifyEqual(result.parameter_names, ...
                string(cases.Properties.VariableNames));
            testCase.verifyEqual(height(result.ranking), 1);
            testCase.verifyTrue(isfinite(result.ranking.lap_time_s));
        end

        function testRealCalibrationIsFrozenAtBaseline(testCase)
            baseConfig = testCase.BaseConfig;
            baselineGgv = generate_model_ggv(baseConfig.vehicle, ...
                baseConfig.models.tire, baseConfig.models.aero, ...
                baseConfig.models.powertrain, baseConfig.models.brake, ...
                baseConfig.options);
            baselineGgv.source = "identity_real_fixture";
            baseConfig.models.ggv_real = baselineGgv;
            sweep.parameter = "vehicle.mass.total_kg";
            sweep.values = [280; 320];

            result = run_sensitivity_sweep(baseConfig, sweep);

            testCase.verifyEqual(result.calibration_mode, "frozen_baseline");
            testCase.verifyNotEqual(result.table.lap_time_s(1), ...
                result.table.lap_time_s(2));
        end
    end
end
