classdef v1ReportingTest < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "src"), IncludingSubfolders=true));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "data"), IncludingSubfolders=true));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, "preprocessing"), ...
                IncludingSubfolders=true));
        end
    end

    methods (Test)
        function testLimiterUsageIsDistanceWeightedAndComplete(testCase)
            result.track.ds_m = [1; 2; 7];
            result.limiter = ["lateral"; "torque"; "coasting"];

            usage = summarize_limiter_usage(result);

            testCase.verifyEqual(sum(usage.percent_distance), 100, ...
                AbsTol=1e-12);
            testCase.verifyEqual(usage.limiter, ...
                ["coasting"; "torque"; "lateral"]);
            testCase.verifyEqual(usage.distance_m, [7; 2; 1], ...
                AbsTol=1e-12);
            testCase.verifyEqual(usage.percent_distance, [70; 20; 10], ...
                AbsTol=1e-12);
        end

        function testLimiterUsageRejectsInvalidLabels(testCase)
            result.track.ds_m = [1; 1];
            result.limiter = ["lateral"; "unexpected_limit"];
            testCase.verifyError(@() summarize_limiter_usage(result), ...
                "QSSLTS:LimiterSummary");

            result.limiter = ["lateral"; ""];
            testCase.verifyError(@() summarize_limiter_usage(result), ...
                "QSSLTS:LimiterSummary");

            result.limiter = ["lateral"; "lateral_infeasible"];
            testCase.verifyError(@() summarize_limiter_usage(result), ...
                "QSSLTS:LimiterSummary");
        end

        function testReproducibleExperimentWritesDoeAndLimiterReports(testCase)
            folderFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);

            report = run_v1_reproducible_experiment( ...
                string(folderFixture.Folder));

            outputPaths = string(struct2cell(report.output_files));
            ranking = readtable(report.output_files.doe_ranking_csv, ...
                TextType="string");
            manifest = jsondecode(fileread( ...
                report.output_files.manifest_json));
            testCase.verifyEqual(height(report.doe.ranking), 27);
            testCase.verifyEqual(height(ranking), 27);
            testCase.verifyTrue(all(isfile(outputPaths)));
            testCase.verifyTrue(report.baseline_result.solver.converged);
            testCase.verifyEqual( ...
                sum(report.baseline_limiter.percent_distance), 100, ...
                AbsTol=1e-10);
            testCase.verifyGreaterThanOrEqual( ...
                diff(report.doe.ranking.lap_time_s), ...
                -1e-12 * ones(26, 1));
            testCase.verifyEqual(string(manifest.schema_version), ...
                "QSSLTS_V1_REPORT_V1");
            testCase.verifyEqual(manifest.doe_case_count, 27);
            testCase.verifyEqual( ...
                manifest.baseline.vehicle.mass.total_kg, 300);
            testCase.verifyEqual(string( ...
                manifest.baseline.tire.model_type), "load_sensitive");
            testCase.verifyEqual(string(manifest.baseline.brake. ...
                max_total_brake_force_N), "Inf");
            testCase.verifyEqual(manifest.baseline.track.s_m, ...
                report.baseline_result.track.s_m);
            testCase.verifyEqual(manifest.baseline.options.v_grid_mps, ...
                report.baseline_result.options.v_grid_mps);
            testCase.verifyTrue(all( ...
                report.doe_case_metrics.solver_converged));
            testCase.verifyTrue(isfinite( ...
                report.baseline_result.lap_time_s));
            testCase.verifyTrue(all(isfinite( ...
                report.doe.ranking.lap_time_s)));
            testCase.verifyEqual(string(manifest.doe.design), ...
                "full_factorial_3x3x3");
            testCase.verifyEqual(manifest.doe.mass_kg, [280; 300; 320]);
            testCase.verifyEqual(manifest.doe.inverter_power_W, ...
                [60000; 80000; 100000]);
            testCase.verifyFalse(isfield(manifest.doe, "max_power_W"));
            testCase.verifyEqual(string( ...
                manifest.baseline.model_functions.powertrain), ...
                "powertrain_emrax228_hvcc_demo");
            testCase.verifyEqual(manifest.baseline.endurance.num_laps, 1);
            testCase.verifyEqual( ...
                manifest.baseline.endurance.safety_factor, 1.0, AbsTol=0);
            testCase.verifyEqual(manifest.doe.tire_mu_scale, ...
                [0.9; 1.0; 1.1]);
            testCase.verifyGreaterThan(strlength(string( ...
                manifest.environment.matlab_release)), 0);
            testCase.verifyGreaterThan(strlength(string( ...
                manifest.environment.computer)), 0);
            sourcePaths = string({ ...
                manifest.code_identity.source_files.path});
            sourceHashes = string({ ...
                manifest.code_identity.source_files.sha256});
            testCase.verifyTrue(any(sourcePaths ...
                == "src/core/run_qss_lap.m"));
            testCase.verifyTrue(any(sourcePaths ...
                == "data/track/simple_track.csv"));
            testCase.verifyTrue(all(strlength(sourceHashes) == 64));
        end
    end
end
